#!/bin/bash

yum update -y

amazon-linux-extras install -y docker

yum install -y git nano sudo

service docker start

usermod -a -G docker ec2-user

mkdir /git

cd /git

git init

git clone https://github.com/tallmantim/dockerbook-code

git clone https://github.com/tallmantim/ite532

